# Generated by Django 2.2 on 2020-05-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pab_date',
            new_name='pub_date',
        ),
    ]
