# Generated by Django 2.2.9 on 2020-05-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200525_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(
                unique=True, verbose_name='Название группыв ссылке'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(
                max_length=200, verbose_name='Название группы'),
        ),
    ]
