# Generated by Django 2.2.9 on 2020-05-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200525_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(unique=True,
                                   verbose_name='Название группы в ссылке'),
        ),
    ]
